
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfApp2
{

using System;
    using System.Collections.Generic;
    
public partial class Contracts
{

    public int id_Contract { get; set; }

    public int id_Client { get; set; }

    public int id_Season_ticket { get; set; }

    public System.DateTime Date_of_conclusion { get; set; }

    public int id_Worker { get; set; }

    public int id_Trainer { get; set; }

    public int Cost { get; set; }

    public int id_Class { get; set; }



    public virtual Clients Clients { get; set; }

    public virtual SeasonTicket SeasonTicket { get; set; }

    public virtual Trainers Trainers { get; set; }

    public virtual Workers Workers { get; set; }

    public virtual Class Class { get; set; }

}

}
